
# Page settings
baseurl = "/"
title = "Das Medium Inc"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = "Das Medium Inc."
  description = "A new way to build and create great things"
  email = "admin@dasmedium.co"
  # Navigation
  [params.navigation]
    brand = "Das Medium"
    home = "Home"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Welcome to Das Medium"
    subtitle = 'A new way to build and create great things.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Plan"
    description = "Take over the world with a great vision. We are looking for the biggest challenges to solve. Execution is the best part of the journey." 
    url = "https://dasmedium.co/contact-us/"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Develop"
    description = "We dont just build and deploy apps for business. You are always part of the development process, no matter your area of expertise."
    url = "https://dasmedium.co/product-category/website-development/"
    button = "Learn More"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Launch"
    description = "Let's make sure every box is ticked, a solid launch always starts with strong vision and realistic approach to development." 
    url = "https://dasmedium.co/about/"
    button = "Why us?"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Services section
  [params.services]
    enable = true
    title = "What we Do"
    description = "We find innovative approaches to do everything. All tools repurposed"

    [[params.services.item]]
      title = "Brand &amp; Strategy"
      description = "Creative designs and concepts for businesses looking to build their brand."
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Web &amp; Interface"
      description = "Multiple deployment formats, one product is its delivery across many platforms and channels. Your content or service delivered from a central locatio.n"
      icon = "icon-layers2"

    [[params.services.item]]
      title = "Photo &amp; Video"
      description = "Multimedia for pitch videos, walk-throughs, video blog templates, video conferencing and video tutorials."
      icon = "icon-video2"

    [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Pre-configured CMS instances for e-learning, e-commerce, social networking and more."      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = true
    title = "About"
    description = "Das Medium aims to be a web development agency and network of business professionals sharing vision, skills and  needs."


    [[params.about.item]]
      name = "Angel Rodriguez"
      position = "Tech Lead"
      description = "Product development and web development focused on e-learning, financial education and business."
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      
    

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = false
    title = "Get in touch"
    description = "Get in contact, collaborate in our projects or give us some feedback."
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Brooklyn, New York"],
        ["icon-phone", "(347) 298-8140"],
        ["icon-envelope", "admin@dasmedium.co"],
        ["icon-globe", '<a href="http://dasmedium.co/shop" target="_blank">Products</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Powered by <a href="http://dasmedium.co/" target="_blank"> Das Medium Inc. </a> <br> Hugo Theme by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co </a>Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]

